## The script was used to run PennCNV on Minerva high performance cluster.
## You need to modifiy it according to the system you are using if you would like to use it.
## Please refer to original PennCNV documents (http://penncnv.openbioinformatics.org/en/latest/) for more information 

### prepare other auxiliary files ###
## a) a text file list_pfb.txt list the samples to be used for compiling pfb file
##    The data file each for one sample is generated by the script finalreport_to_PennCNV.pl
# format of list_pfb.txt: (each data file in one line)
# 1004044.txt
# 1004045.txt
# 1004046.txt
# 1004047.txt
# 1004048.txt
# 1004049.txt

## b) a tab-delimited file SNP_pos.txt which can be generated from final report
# format of SNP_pos.txt: 
# Name    Chr     Position
# 1:10001102-G-T  1       10001102
# 1:100011159-T-G 1       100011159
# 1:10002775-GA   1       10002775
# 1:100122796-C-T 1       100122796

path_to_penncnv=""  ## where PennCNV is installed
wk_dir=""           ## working directory

## compile pfb file
perl ${path_to_penncnv}/compile_pfb.pl \
-listfile #{wk_dir}/list_pfb.txt \
-snpposfile ${wk_dir}/SNP_pos.txt \
-output ${wk_dir}/SNP.pfb

## compile gcmodel file for GC content ajdustment
perl ${path_to_penncnv}/cal_gc_snp.pl \
${wk_dir}/gc5Base_hg19.txt.sorted \ ## please refer to PennCNV documents about how to prepare this data
${wk_dir}/SNP.pfb \
-output SNP.gcmodel

