#!/urs/bin/env Rscript

args <- commandArgs( trailingOnly = TRUE )

path_output    <- args[1]
file_ipattern  <- args[2]
file_penncnv   <- args[3]
file_quantisnp <- args[4]
sample_map     <- args[5]

## Sample_Map.txt can be generated along with final report from Genome Studio
## used to check Sample_ID in the CNV results generated by individual methods

suppressMessages({
  require(data.table)
})

## selected columns from CNV results
col_sel <- c("chr", "posStart", "posEnd", "CN", "Sample_ID", "conf", 
             "numSNP", "avgConf", "length", "CNV_type", "method")

sample <- read.delim(file = sample_map, as.is = TRUE)

# generate data from iPattern, PennCNV, QuantiSNP CNV calls ------------------------

## ipattern ---------------------------------------------------------------------

read_icnv <- function(file_icnv, col_sel, sample) {
  
  cat("Read in CNV calls from iPattern ...\n")
  dat <- read.table(file = file_icnv, sep = "\t", check.names = FALSE, ##skip = 17, 
                    header = FALSE, comment.char = "#",
                    stringsAsFactors = FALSE)
  
  names(dat) <- c("CNV_type", "chr", "posStart", "posEnd",
                  "numSNP", "on_probe.num", "clusterIdx",
                  "gain_loss_score", "cluster_score", "gain_loss_sample.num",
                  "conf", "Sample_ID", "CNV_event_ID", "CNVR_ID")
  dat$length <- dat$posEnd - dat$posStart + 1
  dat$avgConf <- dat$conf/dat$numSNP
    
  # filter chr, CNV_type
  dat <- subset(dat, chr %in% c(1:22) & CNV_type %in% c("Gain", "Loss"))
  dat$CN <- ifelse(dat$CNV_type == "Gain", 3, 1)
  dat$chr <- as.integer(dat$chr)
  dat$method <- "iPattern"
  
  dat$Sample_ID <- gsub("^X", "", dat$Sample_ID, perl = TRUE)
  #dat$Sample_ID <- gsub(".", "-", dat$Sample_ID, fixed = TRUE)

  ## iPattern converts "-" in Sample_ID to "."
  ## recover the original Sample_ID
  idx <- grep("-", sample$ID) 
  samples.raw <- sample$ID[ idx ]
  samples.alt <- sub("-", ".", samples.raw)

  for (i in 1:length(samples.alt)) {
	idxs1 <- which( dat$Sample_ID == samples.alt[i] )
	if (length(idxs1) > 0 ) dat$Sample_ID[ idxs1 ] <- samples.raw[i]
  }

  stopifnot( all(dat$Sample_ID %in% sample$ID) )
  dat[, col_sel]  ## selected columns
}

# merge all groups results
dat_ipattern <- read_icnv( file_icnv = file_ipattern, col_sel = col_sel, sample = sample )

write.table( dat_ipattern, 
             file = file.path(path_output, "cnv.ipattern.txt"),
             quote = F, row.names = F, sep = "\t")


# penncnv -----------------------------------------------------------------

read_pcnv <- function(file_pcnv, col_sel, sample) {
  
  cat("Read in CNV calls from PennCNV ...\n")
  dat <- read.table(file = file_pcnv, sep = "\t", check.names = FALSE,
                    header = FALSE, stringsAsFactors = FALSE, 
                    comment.char = "")
  names(dat) <- c("chr", "posStart", "posEnd", "CN", "Sample_ID", "snpStart", "snpEnd", "conf", "numSNP")
  dat$Sample_ID <- gsub("\\.txt", "", dat$Sample_ID)
  dat$length <- dat$posEnd - dat$posStart + 1
  dat$avgConf <- dat$conf/dat$numSNP
  
  dat <- subset(dat, chr %in% c(1:22) & CN != 2)
  dat$CNV_type <- ifelse(dat$CN > 2, "Gain", "Loss")
  dat$method <- "PennCNV"
  dat$CN[which(dat$CN >= 3)] <- 3 ## set CN >= 3 to CN = 3
  
  stopifnot( all(dat$Sample_ID %in% sample$ID) )
  dat[, col_sel]
}

dat_penncnv <- read_pcnv(file_pcnv = file_penncnv, col_sel = col_sel, sample = sample )

write.table( dat_penncnv, 
             file = file.path(path_output, "cnv.penncnv.txt"),
             quote = F, row.names = F, sep = "\t")


# quantisnp ---------------------------------------------------------------
# read from combined CNV results from all individuals

read_qcnv <- function(file_qcnv, col_sel, sample) {
  
  cat("Read in CNV calls from QuantiSNP ...\n")
  dat <- read.table(file = file_qcnv, 
                    sep = "\t", 
                    header = TRUE, 
                    check.names = FALSE, 
                    stringsAsFactors = FALSE,
                    comment.char = "")
  
  ## change column name Max.log BF => conf
  names(dat) <- c("Sample_ID", "chr", "posStart", "posEnd", "snpStart", "snpEnd", "length", "numSNP", 
                  "CN", "conf", "Log_BF.State.0", "Log_BF.State.1", "Log_BF.State.2", "Log_BF.State.3",
                  "Log_BF.State.4", "Log_BF.State.5", "Log_BF.State.6")
  
  dat <- subset(dat, chr %in% c(1:22) & CN != 2)
  dat$CNV_type <- ifelse(dat$CN > 2, "Gain", "Loss")
  dat$avgConf <- dat$conf/dat$numSNP
  dat$method <- "QuantiSNP"
  dat$CN[which(dat$CN >= 3)] <- 3  # set CN >= 3 to CN = 3
  
  stopifnot( all(dat$Sample_ID %in% sample$ID) )
  dat[, col_sel]
}

dat_quantisnp <- read_qcnv(file_qcnv = file_quantisnp, col_sel = col_sel, sample = sample )

write.table( dat_quantisnp, 
             file = file.path(path_output, "cnv.quantisnp.txt"),
             quote = F, row.names = F, sep = "\t")

